version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: cristian
      POSTGRES_PASSWORD: cristian123
      POSTGRES_DB: proyectoBd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
